back_end/Django/Django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls"))
]

back_end/Django/accounts/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accounts"
urlpatterns = [
    path("profile/", profile, name="profile"),
    path("signin/", signin_view, name="signin"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
]

back_end/Django/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Information(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=11, blank=False, unique=True)

back_end/Django/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SigninForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
    # To ensure that the email entered by a user during the signup process does not already exist in another account
    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use.")
        return email

back_end/Django/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .forms import *


@login_required
def profile(request):
    user = request.user
    return render(request, 'profile.html', {"user": user})

def signin_view(request):
    if request.method == "POST":
        form = SigninForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:login")
    else:
        form = SigninForm()
    return render(request, "signin.html", {"form": form})

def logout_view(request):
    logout(request)
    return redirect(request.META.get("HTTP_REFERER"))

back_end/Django/accounts/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>auctions</title>
</head>
<body>
    <h1>Lets go!</h1>
</body>
</html>

back_end/Django/accounts/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

back_end/Django/accounts/templates/profile.html
{% extends "layout.html" %}
    {% block head %}
        <title>Profile</title>
        <h1>Hello, {{ user.username }}!</h1>
        <h3>Email: {{ user.email }}</h3>
    {% endblock %}

    {% block body %}
        <a href="{% url 'accounts:logout' %}">Logout</a>
    {% endblock %}

back_end/Django/accounts/templates/signin.html
{% extends "layout.html" %}
    {% block head %}
        <title>Sigin</title>
        <h1>Create your account</h1>
    {% endblock %}

    {% block body %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Sign in</button>
        </form>
    {% endblock %}